version: "3.1"

services:
  mongo-dev:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.db.local
    networks:
      - app_network
  mongo:
    image: mongodb/mongodb-community-server
    restart: always
    env_file:
      - .env.db.local
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
